server:
  port: 8082
spring:
  application:
    name: Yummy
  datasource:
    name: postgres
    url: jdbc:postgresql:localhost:5432/yummy
    username: ${POSTGRES_USER:arsen}
    password: ${POSTGRES_PASSWORD:29486}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-Auto: create-drop
    defer-datasource-initialization: true
    showSql: true
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  security:
    user:
      name: arsen
      password: arsenr412
  springdoc:
    api-docs:
      enabled: false

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          description:
            sql:
              BasicBinder: TRACE

application:
  security:
    jwt:
      secret-key: ${SECRET_JWT_KEY}
      expiration: ${JWT_EXPIRATION}
      cookie-name: jwt-cookie
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRATION}
        cookie-name: refresh-jwt-cookie

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
    endpoint:
      health:
        show-details: when-authorized
        show-components: always
    health:
      circuitbreakers:
        enabled: true
      ratelimiters:
        enabled: true